### PR TITLE
Fix/various

### LINKED ISSUE #2211: [client] cat & event stream height
Keep the same min & max height for both tabs

image
Screenshot 2024-12-04 at 10 09 00

### LINKED ISSUE #2520: Bridge lords and resources button should always be on screen
move  from current location / duplicate to top right corner

image

### PR DESCRIPTION
**Pull request by bob0005**
Closes #2211
Closes #2520
Fix add troops

## Summary by CodeRabbit

- **New Features**
  - Introduced a new interactive map icon that streamlines navigation.
  - Added a conditional resource linking button now available for connected users.

- **Bug Fixes**
  - Corrected owner information display in army management.

- **Refactor**
  - Streamlined army details to display accurate owner information and improved troop addition logic.
  - Enhanced the chat interface, enabling dynamic visibility of event feeds.
  - Simplified arrival time displays.
  - Adjusted specific building resource requirements for improved balance.
  - Improved import organization for better code clarity.
  - Refined address retrieval and name decoding processes for enhanced performance.

### CODE REVIEW

File: client/apps/game/src/ui/components/military/army-management-card.tsx [hunk 1]
```diff
@@ -76,10 +75,25 @@ export const ArmyCreate = ({ owner_entity, army, armyManager, isExplorer, guardS
   const handleBuyArmy = async (isExplorer: boolean, troopType: TroopType, troopTier: TroopTier, troopCount: number) => {
     setIsLoading(true);
 
+    const homeDirection =
```
Comment (aymericdelab) [inline client/apps/game/src/ui/components/military/army-management-card.tsx:78]: my point of view is that if something only needs to be used on a click , then compute that thing when user clicks, instead of having it computed every time

**Review by aymericdelab — APPROVED** [review]
