### PR TITLE
Bob client fixes

### LINKED ISSUE #1387: [client] Inform user that raiding while in battle makes them leave

### PR DESCRIPTION
**Pull request by cwastche**
Fixes #1387
fixes hexception centered zoom point
clean up model managers

### CODE REVIEW

**Review by aymericdelab — COMMENTED** [review]
use dojo: SetupResult in all managers

File: client/src/dojo/modelManager/StaminaManager.ts [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+    if (maxStaminas.length === 0) return 0;
+
+    const maxArmyStamina = Math.min(...maxStaminas);
+
+    return maxArmyStamina;
+  };
+
+  private _getStamina() {
+    const entity = runQuery([HasValue(this.dojo.components.Stamina, { entity_id: this.armyEntityId })])
```
Comment (aymericdelab) [inline client/src/dojo/modelManager/StaminaManager.ts:53]: don't use runQuery

**Review by aymericdelab — APPROVED** [review]
