### PR TITLE
various fixes

### LINKED ISSUE #2318: Update image of Realm to the new design
Screenshot 2024-12-09 at 09 42 58

### LINKED ISSUE #2330: [client] empty hyperstructure appearing because of optimistic
image

### LINKED ISSUE #2342: [client] compass to structure
image

### PR DESCRIPTION
**Pull request by bob0005**
Closes #2318
Closes #2330
Closes #2342

## Summary by CodeRabbit

- **New Features**
	- Introduced a new icon representation for the "Bridge in Lords" button.
	- Enhanced the `EntityAvatar` component to dynamically display realm images based on entity ID.
	- Updated filtering logic in the `WorldStructuresMenu` to show relevant hyperstructures and fragment mines based on creation date and ownership.
	- Added expanded search functionality in the `EntityList` to include owner names.
	- Enhanced the `ArmyChip` component for improved troop management and user interaction.

- **Bug Fixes**
	- Improved image selection process for realms to ensure accurate representation.

### CODE REVIEW

File: client/src/ui/modules/world-structures/WorldStructuresMenu.tsx [hunk 1]
```diff
@@ -78,6 +75,7 @@ export const WorldStructuresMenu = ({ className }: { className?: string }) => {
               panel={({ entity }) => <HyperstructurePanel entity={entity} />}
               entityContent={hyperstructureExtraContent}
               list={hyperstructures
+                .filter((hyperstructure) => hyperstructure.created_at)
```
Comment (aymericdelab) [inline client/src/ui/modules/world-structures/WorldStructuresMenu.tsx:78]: why ?
