### PR TITLE
Fix broken lordpedia pages

### LINKED ISSUE #1649: Capacity vs Population
Suggest changing the Lordpedia and the client to say this on Workers Hut 
"Increase max population capacity" or "Increase max population size"

image

image

### PR DESCRIPTION
**Pull request by cwastche**
Closes #1649

### CODE REVIEW

File: client/src/ui/components/hints/TheMap.tsx [hunk 1]
```diff
@@ -54,24 +58,46 @@ const ExplorationTable = () => {
...
+      <tbody>
         <tr>
           <td className="border border-gold/10 p-2 font-bold">Exploration</td>
-          <td className="border border-gold/10 p-2">20</td>
           <td className="border border-gold/10 p-2">
-            <div>Fish: {exploreFishBurn} per unit</div>
-            <div>Wheat: {exploreWheatBurn} per unit</div>
+            <div className="flex flex-row items-center justify-around">
+              <Lightning className="fill-order-power/70 w-8"></Lightning>
+              <p>20</p>
```
Comment (edisontim) [inline client/src/ui/components/hints/TheMap.tsx:67]: Replace with config values 
```
stamina: {
    travelCost: 10,
    exploreCost: 20,
  }
  ```

File: client/src/ui/components/hints/TheMap.tsx [hunk 2]
```diff
@@ -54,24 +58,46 @@ const ExplorationTable = () => {
...
         </tr>
         <tr>
           <td className="border border-gold/10 p-2 font-bold">Travel</td>
-          <td className="border border-gold/10 p-2">10</td>
           <td className="border border-gold/10 p-2">
-            <div>Fish: {travelFishBurn} per unit</div>
-            <div>Wheat: {travelWheatBurn} per unit</div>
+            <div className="flex flex-row items-center justify-around">
+              <Lightning className="fill-order-power/70 w-8"></Lightning>
+              <p>10</p>
```
Comment (edisontim) [inline client/src/ui/components/hints/TheMap.tsx:86]: Replace with config values 
```
stamina: {
    travelCost: 10,
    exploreCost: 20,
  }
  ```

**Review by edisontim — CHANGES_REQUESTED** [review]

**Review by edisontim — APPROVED** [review]
lgtm
