### PR TITLE
Fix quests rerendering perf

### LINKED ISSUE #1102: Settle Quest isn't claimable -
i click to claim, the button spins. no transaction is show on the bottom right of the screen.

image

### PR DESCRIPTION
**Pull request by cwastche**
### **PR Type**
Enhancement, Bug fix

Closes #1102
___

### **Description**
- Introduced a new `useQuests` hook to manage quest-related logic, including quest definitions, statuses, and dependencies.
- Simplified `useQuestStore` to manage only the selected quest state, removing redundant quest-related logic.
- Refactored various components to integrate the new `useQuests` and `useQuestClaimStatus` hooks, updating visibility and notification logic accordingly.
- Added a new function `useArmiesCanMoveCount` in `useStamina` to determine the number of armies that can move.
- Updated utility functions and quest-related conditions across multiple components to align with the new quest status logic.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>15 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>useQuests.tsx</strong><dd><code>Introduce `useQuests` hook for quest management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/hooks/helpers/useQuests.tsx

<li>Added new <code>useQuests</code> hook to manage quest-related logic.<br> <li> Defined <code>QuestName</code>, <code>QuestStatus</code>, and <code>Prize</code> enums and interfaces.<br> <li> Implemented memoized quest objects and their dependencies.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-02207afc6e5bd13a56e092c44f234cbddae30dd5cf9704eb786a3b8f7da20d33">+485/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>useStamina.tsx</strong><dd><code>Add function to count armies that can move</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/hooks/helpers/useStamina.tsx

<li>Added <code>useArmiesCanMoveCount</code> function to determine movable armies.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-1462ae4521465368a66e185d64e149c741cf0439b84171e3946f3fa1046b8764">+14/-1</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>useQuestStore.tsx</strong><dd><code>Simplify `useQuestStore` to manage selected quest state</code>&nbsp; &nbsp; </dd></summary>
<hr>

client/src/hooks/store/useQuestStore.tsx

<li>Simplified <code>useQuestStore</code> to manage only selected quest state.<br> <li> Removed redundant quest-related logic.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-a7c36ca377844946d158e339e652e7588b89111d70276c01cf716ce0dea0c9da">+7/-344</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>HooksComponent.tsx</strong><dd><code>Remove `useQuests` hook call from HooksComponent</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/ui/components/HooksComponent.tsx

- Removed `useQuests` hook call.

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-43043be932b2633420880f87aadca8729c0fd8f71fe5cfa30995c1859d4ba784">+0/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>SelectPreviewBuilding.tsx</strong><dd><code>Refactor quest claim status logic in SelectPreviewBuilding</code></dd></summary>
<hr>

client/src/ui/components/construction/SelectPreviewBuilding.tsx

<li>Refactored quest claim status logic.<br> <li> Updated visibility conditions for building cards.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-c6a222463602fe87932fbbc060d2d99cdd1b151dcb9fcd9be42b602a77f18d97">+6/-11</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>ArmyList.tsx</strong><dd><code>Update quest conditions for army creation in ArmyList</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/ui/components/military/ArmyList.tsx

- Updated quest-related conditions for army creation.

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-19286ac1f005ea8e13dda2e8ba0752bff5920fcf501f94c636608e4b6f4466a3">+4/-7</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>QuestInfo.tsx</strong><dd><code>Refactor quest status display and reward claim logic in QuestInfo</code></dd></summary>
<hr>

client/src/ui/components/quest/QuestInfo.tsx

<li>Refactored quest status display logic.<br> <li> Updated reward claim button conditions.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-bfa702fa0e90351e6ba9558eb10bd9dffb14de1e98e8ec2ff1af05f59ded92c5">+19/-12</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>QuestList.tsx</strong><dd><code>Refactor quest grouping and display logic in QuestList</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/ui/components/quest/QuestList.tsx

<li>Refactored quest grouping and display logic.<br> <li> Updated state management for showing completed quests.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-fa146485a21bbcfa64629adc96f95bebb3d3e36c85f4705ca5c3ed26ddb51221">+16/-13</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>QuestPanel.tsx</strong><dd><code>Integrate <code>useQuests</code> hook and update quest selection logic in <br>QuestPanel</code></dd></summary>
<hr>

client/src/ui/components/quest/QuestPanel.tsx

<li>Integrated <code>useQuests</code> hook for quest data.<br> <li> Updated quest selection logic.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-95490c886fb9e43c63caf1df7f6b8a28812e42e2ca2dc5a9d104f4994caa4ef4">+8/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>utils.tsx</strong><dd><code>Update utility functions for new quest status logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/ui/components/quest/utils.tsx

- Updated utility functions to use new quest status logic.

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-e24ff117ce2379e0c16ec97fa39a255c364cd262544b3a249428c917c59b468e">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>StructureConstructionMenu.tsx</strong><dd><code>Refactor quest claim status logic in StructureConstructionMenu</code></dd></summary>
<hr>

client/src/ui/components/structures/construction/StructureConstructionMenu.tsx

- Refactored quest claim status logic.

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-5274bf9e1bf9eee6c0d7a1aabeadb3eadefabe6049a2d10695e172409c70637a">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>BottomNavigation.tsx</strong><dd><code>Integrate quest hooks and update notification logic in </code><br><code>BottomNavigation</code></dd></summary>
<hr>

client/src/ui/modules/navigation/BottomNavigation.tsx

<li>Integrated <code>useQuests</code> and <code>useQuestClaimStatus</code> hooks.<br> <li> Updated notification logic for quests.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-e88ab2bf26cead1655ae59538674a03ae7a573c4c6ea347a8ad382f197b3cc4d">+21/-11</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>LeftNavigationModule.tsx</strong><dd><code>Integrate quest claim status hook and update navigation logic in </code><br><code>LeftNavigationModule</code></dd></summary>
<hr>

client/src/ui/modules/navigation/LeftNavigationModule.tsx

<li>Integrated <code>useQuestClaimStatus</code> hook.<br> <li> Updated visibility and notification logic for navigation buttons.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-be9e8648ba688d13b3b68afca51d87c31cca8d9412f8c7d77edee0d71737a287">+13/-16</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>RightNavigationModule.tsx</strong><dd><code>Integrate quest claim status hook and update navigation logic in </code><br><code>RightNavigationModule</code></dd></summary>
<hr>

client/src/ui/modules/navigation/RightNavigationModule.tsx

<li>Integrated <code>useQuestClaimStatus</code> hook.<br> <li> Updated visibility and notification logic for navigation buttons.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-8b98807e05dc7525757f9d43f5a3b1a081305f54aa3be0d5be4b2a130160bd0c">+11/-8</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>TopMiddleNavigation.tsx</strong><dd><code>Update quest conditions for navigation buttons in TopMiddleNavigation</code></dd></summary>
<hr>

client/src/ui/modules/navigation/TopMiddleNavigation.tsx

- Updated quest-related conditions for navigation buttons.

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1114/files#diff-98461a600ecf71fa8776ed334c66d832ea531c99b49221910e7aea02abe61b95">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

File: client/src/ui/modules/navigation/LeftNavigationModule.tsx [hunk 1]
```diff
@@ -197,7 +193,8 @@ export const LeftNavigationModule = () => {
             item.name === MenuEnum.construction ||
             item.name === MenuEnum.worldStructures,
         );
-  }, [location, view, armiesWithStaminaLeft, quests, openedPopups]);
+  }, [location, view, openedPopups, selectedQuest, armiesCanMoveCount]);
+  // }, [location, view, armiesWithStaminaLeft, openedPopups]);
```
Comment (edisontim) [inline client/src/ui/modules/navigation/LeftNavigationModule.tsx:197]: remove comment

File: client/src/hooks/helpers/useQuests.tsx [hunk 2]
```diff
@@ -0,0 +1,485 @@
...
+            : QuestStatus.Completed
+          : QuestStatus.InProgress,
+      steps: [
+        "Navigate to the construction menu",
+        "Select the 'Farm' card",
+        "Left click on a hex to build it, or right click to cancel",
+      ],
+      prizes: questPrize.get(QuestName.BuildFarm) || [],
+      depth: 1,
+    }),
```
Comment (edisontim) [inline client/src/hooks/helpers/useQuests.tsx:115]: except for the status, can we merge all of this information with the QuestPrize object and put this in another file? It would make this one way more readable imo

File: client/src/hooks/helpers/useQuests.tsx [hunk 3]
```diff
@@ -0,0 +1,485 @@
...
+  const {
+    setup: {
+      components: { Contribution, EntityOwner },
+    },
+    account: { account },
+  } = useDojo();
+
+  const { playerRealms } = useEntities();
+  const realm = playerRealms()[0];
+  const realmEntityId = realm?.entity_id;
```
Comment (edisontim) [inline client/src/hooks/helpers/useQuests.tsx:336]: memoize this

File: client/src/hooks/helpers/useQuests.tsx [hunk 4]
```diff
@@ -0,0 +1,485 @@
...
+export const useQuestClaimStatus = () => {
+  const {
+    setup: {
+      components: { HasClaimedStartingResources, EntityOwner },
+    },
+  } = useDojo();
+
+  const { playerRealms } = useEntities();
+  const realm = playerRealms()[0];
+  const realmEntityId = realm?.entity_id;
```
Comment (edisontim) [inline client/src/hooks/helpers/useQuests.tsx:408]: memoize this

File: client/src/hooks/helpers/useQuests.tsx [hunk 5]
```diff
@@ -0,0 +1,619 @@
...
+  title: string;
+}
+
+export enum QuestStatus {
+  InProgress,
+  Completed,
+  Claimed,
+}
+
+const questInfo = new Map<QuestName, StaticQuestInfo>([
```
Comment (edisontim) [inline client/src/hooks/helpers/useQuests.tsx:54]: Move this to a different file

**Review by edisontim — APPROVED** [review]
lgtm
