### PR TITLE
fix army weight when exploring, add weigh + capacity in UI

### LINKED ISSUE #1078: [client] review capacity limits for armies
check the capacity limit for the army and add check to avoid exploration in client if max capacity reached

### PR DESCRIPTION
**Pull request by cwastche**
### **User description**
Closes #1078

___

### **PR Type**
Enhancement, Bug fix

___

### **Description**
- Added `capacity` and `weight` properties to `ArmyInfo` type and included `Weight` component in various hooks and functions.
- Created `ArmyCapacity` component to display army capacity and weight.
- Updated `setCapacityConfig` to remove precision modification for army weight.
- Added `ArmyCapacity` component to display army capacity in multiple UI components including `Entity`, `ArmyChip`, `ArmyList`, and `ArmyInfoLabel`.
- Added reward display for exploration in `ActionInfo` component.
- Added capacity check for exploration in `useTravelPath` hook and `canExplore` function.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>useArmies.tsx</strong><dd><code>Add weight and capacity properties to ArmyInfo type</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/hooks/helpers/useArmies.tsx

<li>Added <code>capacity</code> and <code>weight</code> properties to <code>ArmyInfo</code> type.<br> <li> Included <code>Weight</code> component in various hooks and functions.<br> <li> Calculated and set <code>capacity</code> and <code>weight</code> values in <code>formatArmies</code> <br>function.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1117/files#diff-6d68c14fbe3262def9a16f121115d2006c7c34bf942b3e5d8ed7c076d2b89027">+26/-2</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Entity.tsx</strong><dd><code>Display army capacity in Entity component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/ui/components/entities/Entity.tsx

- Added `ArmyCapacity` component to display army capacity in the UI.

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1117/files#diff-e41f7ca60992e606521c1c7a6cda0e416abefc1bc9ec7d0716bc4037a6cb1c43">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>ArmyChip.tsx</strong><dd><code>Display army capacity in ArmyChip component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/ui/components/military/ArmyChip.tsx

<li>Added <code>ArmyCapacity</code> component to display army capacity in the ArmyChip <br>component.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1117/files#diff-9392efc502d8dd91125b44c0f8a38789aa297e674db0538a8893fb6ab9bd7487">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>ArmyList.tsx</strong><dd><code>Display army capacity in ArmyList component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/ui/components/military/ArmyList.tsx

<li>Added <code>ArmyCapacity</code> component to display army capacity in the ArmyList <br>component.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1117/files#diff-19286ac1f005ea8e13dda2e8ba0752bff5920fcf501f94c636608e4b6f4466a3">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>ArmyInfoLabel.tsx</strong><dd><code>Display army capacity in ArmyInfoLabel component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx

<li>Added <code>ArmyCapacity</code> component to display army capacity in the <br>ArmyInfoLabel component.<br> <li> Updated army data using <code>useArmyByArmyEntityId</code> hook.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1117/files#diff-cd50a2982e2719f8bbd53e53abb05c46ada8015f280b32a89290525129aa8d73">+7/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>ActionInfo.tsx</strong><dd><code>Display exploration reward in ActionInfo component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/ui/components/worldmap/hexagon/ActionInfo.tsx

- Added reward display for exploration in ActionInfo component.

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1117/files#diff-a6e30c035b2ca9664f95123bf217ac2e3f2b41baabc17fcae4d8edd1c71b5fe1">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>useTravelPath.tsx</strong><dd><code>Add capacity check for exploration in useTravelPath hook</code>&nbsp; </dd></summary>
<hr>

client/src/ui/components/worldmap/hexagon/useTravelPath.tsx

- Added capacity check for exploration in useTravelPath hook.

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1117/files#diff-2c0f825b699a1aa89a0e106d3bdef659bf441eb6239e41ffe08cd04d43600361">+8/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>utils.tsx</strong><dd><code>Add capacity check in canExplore function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

client/src/ui/components/worldmap/hexagon/utils.tsx

- Added capacity check in `canExplore` function.

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1117/files#diff-770c44daa009ae4d3637fe48f885dfddf3ed664920aca4d4367177be3a83bcb0">+4/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>ArmyCapacity.tsx</strong><dd><code>Create ArmyCapacity component to display capacity and weight</code></dd></summary>
<hr>

client/src/ui/elements/ArmyCapacity.tsx

<li>Created <code>ArmyCapacity</code> component to display army capacity and weight.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1117/files#diff-435326e1d050e2ed1d696a3d29c9c4de452843ddd4c87b05d194989b9f73a953">+16/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Bug fix</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Update setCapacityConfig to remove precision modification</code></dd></summary>
<hr>

sdk/packages/eternum/src/config/index.ts

<li>Updated <code>setCapacityConfig</code> to remove precision modification for army <br>weight.<br>

</details>

  </td>
  <td><a href="https://github.com/BibliothecaDAO/eternum/pull/1117/files#diff-6aecc823aea65bfad1461922fd49c884b2c705a136856aecefc623f166212043">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

File: client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx [hunk 1]
```diff
@@ -42,10 +43,11 @@ const RaiderInfo = ({ army }: ArmyInfoLabelProps) => {
     account: { account },
   } = useDojo();
 
+  const updatedArmy = useArmyByArmyEntityId(BigInt(army.entity_id));
```
Comment (edisontim) [inline client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx:46]: Do we really need to use another `useEntityQuery` here? We already have the army passed as props

**Review by edisontim — APPROVED** [review]
lgtm

**Review by edisontim — APPROVED** [review]

**Review by edisontim — APPROVED** [review]
